type Transaction {
  id: ID!
  account: String!
  description: String
  category: String
  reference: String
  currency: String!
  amount: Float!
  status: String!
  transactionDate: String!
  createdAt: String!
  updatedAt: String!
}

type Query {
  getAllTransactions: [Transaction!]
  getTransactionsByDate(startMonth: String, endMonth: String): [Transaction!]
  getTransactionById(transactionId: String): Transaction
}